const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
const SORT_MOVIE_BY = 'SORT_MOVIE_BY';
const FILTER_MOVIE_BY = 'FILTER_MOVIE_BY';
const GET_MOVIE_LIST_PENDING = 'GET_MOVIE_LIST_PENDING';

export {
  GET_MOVIE_LIST, SORT_MOVIE_BY, FILTER_MOVIE_BY, GET_MOVIE_LIST_PENDING,
};
