export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
export const ADD_MOVIE = 'ADD_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
export const SORT_MOVIE_BY = 'SORT_MOVIE_BY';
export const FILTER_MOVIE_BY = 'FILTER_MOVIE_BY';
export const GET_MOVIE_LIST_PENDING = 'GET_MOVIE_LIST_PENDING';
